"""empty message

Revision ID: 2d533ebacf10
Revises: 06f1ff7fb3d9
Create Date: 2025-04-17 01:20:45.229290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d533ebacf10'
down_revision = '06f1ff7fb3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_boy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('current_location_lat', sa.Float(), nullable=True),
    sa.Column('current_location_lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_boy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_location_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_location_lng', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'delivery_boy', ['delivery_boy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_location_lng')
        batch_op.drop_column('current_location_lat')
        batch_op.drop_column('delivery_boy_id')

    op.drop_table('delivery_boy')
    # ### end Alembic commands ###
